In [1]:
from sklearn.preprocessing import PolynomialFeatures
import numpy as np

In [3]:
X = np.arange(4).reshape(2, 2)
X

array([[0, 1],
       [2, 3]])

In [4]:
poly = PolynomialFeatures(degree=2)
poly.fit_transform(X)

array([[ 1.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  2.,  3.,  4.,  6.,  9.]])

`[x1, x2] -> [1, x1, x2, x1 ** 2, x1 * x2, x2 ** 2]`

In [5]:
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline

In [6]:
model = Pipeline([('poly', PolynomialFeatures(degree=3)),
                  ('linear', LinearRegression(fit_intercept=False))])

In [8]:
x = np.arange(5)
y = 3 - 2 * x + x ** 2 - x ** 3
np.stack([x, y])

array([[  0,   1,   2,   3,   4],
       [  3,   1,  -5, -21, -53]])

In [9]:
model.fit(x[:, None], y)

Pipeline(memory=None,
     steps=[('poly', PolynomialFeatures(degree=3, include_bias=True, interaction_only=False)), ('linear', LinearRegression(copy_X=True, fit_intercept=False, n_jobs=1, normalize=False))])

In [11]:
model.named_steps['linear'].coef_

array([ 3., -2.,  1., -1.])