In [1]:
import pandas as pd
import numpy as np
from sklearn import datasets
from sklearn.decomposition import PCA

In [2]:
iris = datasets.load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)

In [3]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [4]:
df_norm = (df - df.mean()) / df.std()

In [5]:
pca = PCA(n_components=4)
pca.fit_transform(df_norm.values)

array([[ -2.25698063e+00,   5.04015404e-01,  -1.21536190e-01,
         -2.29962838e-02],
       [ -2.07945912e+00,  -6.53216394e-01,  -2.26492063e-01,
         -1.02863642e-01],
       [ -2.36004408e+00,  -3.17413945e-01,   5.13077379e-02,
         -2.77323192e-02],
       [ -2.29650366e+00,  -5.73446613e-01,   9.85303586e-02,
          6.60900544e-02],
       [ -2.38080159e+00,   6.72514411e-01,   2.13563034e-02,
          3.72724209e-02],
       [ -2.06362348e+00,   1.51347827e+00,   3.05818064e-02,
         -4.38408784e-03],
       [ -2.43754534e+00,   7.43137171e-02,   3.41055070e-01,
          3.79693659e-02],
       [ -2.22638327e+00,   2.46787172e-01,  -8.22987560e-02,
          2.54200029e-02],
       [ -2.33413810e+00,  -1.09148977e+00,   1.53049668e-01,
          2.67043670e-02],
       [ -2.18136797e+00,  -4.47131117e-01,  -2.45736283e-01,
          3.97740567e-02],
       [ -2.15626287e+00,   1.06702096e+00,  -2.63127870e-01,
         -1.52500486e-02],
       [ -2.31960686e

In [6]:
pca.explained_variance_ratio_

array([ 0.72770452,  0.23030523,  0.03683832,  0.00515193])

In [7]:
np.identity(df.shape[1])

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [8]:
components = pca.transform(np.identity(df.shape[1]))

In [10]:
pd.DataFrame(components, columns=['pc_1', 'pc_2', 'pc_3', 'pc_4'], index = df.columns)

pc_1      pc_2      pc_3      pc_4
sepal length (cm)  0.522372  0.372318 -0.721017 -0.261996
sepal width (cm)  -0.263355  0.925556  0.242033  0.124135
petal length (cm)  0.581254  0.021095  0.140892  0.801154
petal width (cm)   0.565611  0.065416  0.633801 -0.523546